#include "input/nebu_system_keynames.h"
#include "input/nebu_input_system.h"

custom_keynames custom_keys = {
 { 
	 {  SYSTEM_JOY_LEFT, "joy0 left" },
	 {  SYSTEM_JOY_RIGHT, "joy0 right" },
	 {  SYSTEM_JOY_UP, "joy0 up" },
	 {  SYSTEM_JOY_DOWN, "joy0 down" },
	 {  SYSTEM_JOY_BUTTON_0, "joy0 button 0" },
	 {  SYSTEM_JOY_BUTTON_1, "joy0 button 1" },
	 {  SYSTEM_JOY_BUTTON_2, "joy0 button 2" },
	 {  SYSTEM_JOY_BUTTON_3, "joy0 button 3" },
	 {  SYSTEM_JOY_BUTTON_4, "joy0 button 4" },
	 {  SYSTEM_JOY_BUTTON_5, "joy0 button 5" },
	 {  SYSTEM_JOY_BUTTON_6, "joy0 button 6" },
	 {  SYSTEM_JOY_BUTTON_7, "joy0 button 7" },
	 {  SYSTEM_JOY_BUTTON_8, "joy0 button 8" },
	 {  SYSTEM_JOY_BUTTON_9, "joy0 button 9" },
	 {  SYSTEM_JOY_BUTTON_10, "joy0 button 10" },
	 {  SYSTEM_JOY_BUTTON_11, "joy0 button 11" },
	 {  SYSTEM_JOY_BUTTON_12, "joy0 button 12" },
	 {  SYSTEM_JOY_BUTTON_13, "joy0 button 13" },
	 {  SYSTEM_JOY_BUTTON_14, "joy0 button 14" },
	 {  SYSTEM_JOY_BUTTON_15, "joy0 button 15" },
	 {  SYSTEM_JOY_BUTTON_16, "joy0 button 16"  },
	 {  SYSTEM_JOY_BUTTON_17, "joy0 button 17" },
	 {  SYSTEM_JOY_BUTTON_18, "joy0 button 18" },
	 {  SYSTEM_JOY_BUTTON_19, "joy0 button 19" },
	 {  SYSTEM_JOY_LEFT + SYSTEM_JOY_OFFSET, "joy1 left" },
	 {  SYSTEM_JOY_RIGHT + SYSTEM_JOY_OFFSET, "joy1 right" },
	 {  SYSTEM_JOY_UP + SYSTEM_JOY_OFFSET, "joy1 up" },
	 {  SYSTEM_JOY_DOWN + SYSTEM_JOY_OFFSET, "joy1 down" },
	 {  SYSTEM_JOY_BUTTON_0 + SYSTEM_JOY_OFFSET, "joy1 button 0" },
	 {  SYSTEM_JOY_BUTTON_1 + SYSTEM_JOY_OFFSET, "joy1 button 1" },
	 {  SYSTEM_JOY_BUTTON_2 + SYSTEM_JOY_OFFSET, "joy1 button 2" },
	 {  SYSTEM_JOY_BUTTON_3 + SYSTEM_JOY_OFFSET, "joy1 button 3" },
	 {  SYSTEM_JOY_BUTTON_4 + SYSTEM_JOY_OFFSET, "joy1 button 4" },
	 {  SYSTEM_JOY_BUTTON_5 + SYSTEM_JOY_OFFSET, "joy1 button 5" },
	 {  SYSTEM_JOY_BUTTON_6 + SYSTEM_JOY_OFFSET, "joy1 button 6" },
	 {  SYSTEM_JOY_BUTTON_7 + SYSTEM_JOY_OFFSET, "joy1 button 7" },
	 {  SYSTEM_JOY_BUTTON_8 + SYSTEM_JOY_OFFSET, "joy1 button 8" },
	 {  SYSTEM_JOY_BUTTON_9 + SYSTEM_JOY_OFFSET, "joy1 button 9" },
	 {  SYSTEM_JOY_BUTTON_10 + SYSTEM_JOY_OFFSET, "joy1 button 10" },
	 {  SYSTEM_JOY_BUTTON_11 + SYSTEM_JOY_OFFSET, "joy1 button 11" },
	 {  SYSTEM_JOY_BUTTON_12 + SYSTEM_JOY_OFFSET, "joy1 button 12" },
	 {  SYSTEM_JOY_BUTTON_13 + SYSTEM_JOY_OFFSET, "joy1 button 13" },
	 {  SYSTEM_JOY_BUTTON_14 + SYSTEM_JOY_OFFSET, "joy1 button 14" },
	 {  SYSTEM_JOY_BUTTON_15 + SYSTEM_JOY_OFFSET, "joy1 button 15" },
	 {  SYSTEM_JOY_BUTTON_16 + SYSTEM_JOY_OFFSET, "joy1 button 16"  },
	 {  SYSTEM_JOY_BUTTON_17 + SYSTEM_JOY_OFFSET, "joy1 button 17" },
	 {  SYSTEM_JOY_BUTTON_18 + SYSTEM_JOY_OFFSET, "joy1 button 18" },
	 {  SYSTEM_JOY_BUTTON_19 + SYSTEM_JOY_OFFSET, "joy1 button 19" },
	 {  SYSTEM_JOY_LEFT + SYSTEM_JOY_OFFSET*2, "joy2 left" },
	 {  SYSTEM_JOY_RIGHT + SYSTEM_JOY_OFFSET*2, "joy2 right" },
	 {  SYSTEM_JOY_UP + SYSTEM_JOY_OFFSET*2, "joy2 up" },
	 {  SYSTEM_JOY_DOWN + SYSTEM_JOY_OFFSET*2, "joy2 down" },
	 {  SYSTEM_JOY_BUTTON_0 + SYSTEM_JOY_OFFSET*2, "joy2 button 0" },
	 {  SYSTEM_JOY_BUTTON_1 + SYSTEM_JOY_OFFSET*2, "joy2 button 1" },
	 {  SYSTEM_JOY_BUTTON_2 + SYSTEM_JOY_OFFSET*2, "joy2 button 2" },
	 {  SYSTEM_JOY_BUTTON_3 + SYSTEM_JOY_OFFSET*2, "joy2 button 3" },
	 {  SYSTEM_JOY_BUTTON_4 + SYSTEM_JOY_OFFSET*2, "joy2 button 4" },
	 {  SYSTEM_JOY_BUTTON_5 + SYSTEM_JOY_OFFSET*2, "joy2 button 5" },
	 {  SYSTEM_JOY_BUTTON_6 + SYSTEM_JOY_OFFSET*2, "joy2 button 6" },
	 {  SYSTEM_JOY_BUTTON_7 + SYSTEM_JOY_OFFSET*2, "joy2 button 7" },
	 {  SYSTEM_JOY_BUTTON_8 + SYSTEM_JOY_OFFSET*2, "joy2 button 8" },
	 {  SYSTEM_JOY_BUTTON_9 + SYSTEM_JOY_OFFSET*2, "joy2 button 9" },
	 {  SYSTEM_JOY_BUTTON_10 + SYSTEM_JOY_OFFSET*2, "joy2 button 10" },
	 {  SYSTEM_JOY_BUTTON_11 + SYSTEM_JOY_OFFSET*2, "joy2 button 11" },
	 {  SYSTEM_JOY_BUTTON_12 + SYSTEM_JOY_OFFSET*2, "joy2 button 12" },
	 {  SYSTEM_JOY_BUTTON_13 + SYSTEM_JOY_OFFSET*2, "joy2 button 13" },
	 {  SYSTEM_JOY_BUTTON_14 + SYSTEM_JOY_OFFSET*2, "joy2 button 14" },
	 {  SYSTEM_JOY_BUTTON_15 + SYSTEM_JOY_OFFSET*2, "joy2 button 15" },
	 {  SYSTEM_JOY_BUTTON_16 + SYSTEM_JOY_OFFSET*2, "joy2 button 16"  },
	 {  SYSTEM_JOY_BUTTON_17 + SYSTEM_JOY_OFFSET*2, "joy2 button 17" },
	 {  SYSTEM_JOY_BUTTON_18 + SYSTEM_JOY_OFFSET*2, "joy2 button 18" },
	 {  SYSTEM_JOY_BUTTON_19 + SYSTEM_JOY_OFFSET*2, "joy2 button 19" },
	 {  SYSTEM_JOY_LEFT + SYSTEM_JOY_OFFSET*3, "joy3 left" },
	 {  SYSTEM_JOY_RIGHT + SYSTEM_JOY_OFFSET*3, "joy3 right" },
	 {  SYSTEM_JOY_UP + SYSTEM_JOY_OFFSET*3, "joy3 up" },
	 {  SYSTEM_JOY_DOWN + SYSTEM_JOY_OFFSET*3, "joy3 down" },
	 {  SYSTEM_JOY_BUTTON_0 + SYSTEM_JOY_OFFSET*3, "joy3 button 0" },
	 {  SYSTEM_JOY_BUTTON_1 + SYSTEM_JOY_OFFSET*3, "joy3 button 1" },
	 {  SYSTEM_JOY_BUTTON_2 + SYSTEM_JOY_OFFSET*3, "joy3 button 2" },
	 {  SYSTEM_JOY_BUTTON_3 + SYSTEM_JOY_OFFSET*3, "joy3 button 3" },
	 {  SYSTEM_JOY_BUTTON_4 + SYSTEM_JOY_OFFSET*3, "joy3 button 4" },
	 {  SYSTEM_JOY_BUTTON_5 + SYSTEM_JOY_OFFSET*3, "joy3 button 5" },
	 {  SYSTEM_JOY_BUTTON_6 + SYSTEM_JOY_OFFSET*3, "joy3 button 6" },
	 {  SYSTEM_JOY_BUTTON_7 + SYSTEM_JOY_OFFSET*3, "joy3 button 7" },
	 {  SYSTEM_JOY_BUTTON_8 + SYSTEM_JOY_OFFSET*3, "joy3 button 8" },
	 {  SYSTEM_JOY_BUTTON_9 + SYSTEM_JOY_OFFSET*3, "joy3 button 9" },
	 {  SYSTEM_JOY_BUTTON_10 + SYSTEM_JOY_OFFSET*3, "joy3 button 10" },
	 {  SYSTEM_JOY_BUTTON_11 + SYSTEM_JOY_OFFSET*3, "joy3 button 11" },
	 {  SYSTEM_JOY_BUTTON_12 + SYSTEM_JOY_OFFSET*3, "joy3 button 12" },
	 {  SYSTEM_JOY_BUTTON_13 + SYSTEM_JOY_OFFSET*3, "joy3 button 13" },
	 {  SYSTEM_JOY_BUTTON_14 + SYSTEM_JOY_OFFSET*3, "joy3 button 14" },
	 {  SYSTEM_JOY_BUTTON_15 + SYSTEM_JOY_OFFSET*3, "joy3 button 15" },
	 {  SYSTEM_JOY_BUTTON_16 + SYSTEM_JOY_OFFSET*3, "joy3 button 16"  },
	 {  SYSTEM_JOY_BUTTON_17 + SYSTEM_JOY_OFFSET*3, "joy3 button 17" },
	 {  SYSTEM_JOY_BUTTON_18 + SYSTEM_JOY_OFFSET*3, "joy3 button 18" },
	 {  SYSTEM_JOY_BUTTON_19 + SYSTEM_JOY_OFFSET*3, "joy3 button 19" } 
 }
};
